# Generated by Django 4.1.4 on 2022-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
